language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_install:
  - sudo apt-get install -y sshpass
script:
  - npm install
  - npm run lint
  - npm run build
  - sshpass -p "$DEPLOY_PASSWORD" scp -o StrictHostKeyChecking=no -P $DEPLOY_PORT -r ./build $DEPLOY_USER@$DEPLOY_ADDR:/var/www/ai/html
addons:
  ssh_known_hosts:
    - $DEPLOY_ADDR:$DEPLOY_PORT
